chimeil:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 39.105.158.36
    port: 3306
    database: chimeil
    username: remote_user
    password: 1526942542.Lh


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t66cHDD6YxwJYhdrVa4
    access-key-secret: SSlGPVeDav9mHPRYt1aKH0zhgr
    bucket-name: chaojiyk

  redis:
    host: 39.105.158.36
    port: 6379
    password: Redis@123456
    database: 0

  wechat:
    appid: wx380bfb7f0e067979
    secret: 19aeea8ee54a91adc095bd035a1228ae
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
